### ISSUE TITLE
Bug in dumper.rb

### ISSUE THREAD

**Issue by jasonadamyoung** [extension/albatross#65]
`/services/engineering/current/script/dumper.rb:48:in `block in daily': undefined method `success?' for {:success=>false, :error=>"Dump already in progress"}:Hash (NoMethodError)
	from /services/engineering/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.2/lib/active_record/relation/delegation.rb:6:in `each'
	from /services/engineering/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22.2/lib/active_record/relation/delegation.rb:6:in `each'
	from /services/engineering/current/script/dumper.rb:45:in `daily'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /services/engineering/current/script/dumper.rb:67:in `<main>'`

**Comment by jasonadamyoung** [comment]
I may have upgraded out of this.
